version: '3'
services:
    node-client:
        build:
            dockerfile: ./docker/client.dockerfile
            context: .
        image: gdp/node-client
        volumes:
            - ${PWD}/client/:/var/www
        container_name: container-node-client
        ports:
            - "3000:3000"
        networks:
            - gdp-network
        depends_on:
            - "node-server"
        command: bash -c "npm install && npm start"

    node-server:
        build:
            dockerfile: ./docker/server.dockerfile
            context: .
        image: gdp/node-server
        volumes:
            - ${PWD}/server/:/var/www
        container_name: container-node-server
        ports:
            - "5000:5000"
        networks:
            - gdp-network
        command: bash -c "npm install && npm start"

networks:
    gdp-network:
        driver: bridge
