export const ADD_ITEM = 'ADD_ITEM';
export const FETCH_PRICING_RULES_REQUEST = 'FETCH_PRICING_RULES_REQUEST';
export const FETCH_PRICING_RULES_SUCCESS = 'FETCH_PRICING_RULES_SUCCESS';
export const FETCH_PRICING_RULES_FAILURE = 'FETCH_PRICING_RULES_FAILURE';
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const REMOVE_ITEM = 'REMOVE_ITEM';
